import { useState, useEffect} from 'react';
import * as toxicity from '@tensorflow-models/toxicity';


import Head from 'next/head'

import Image from "next/image";

export default function Home() {

  useEffect(()=> {
    const threshold = 0.9;

    // Which toxicity labels to return.
    const labelsToInclude = ['identity_attack', 'insult', 'threat'];

    toxicity.load(threshold, labelsToInclude).then(model => {
      console.log(model)
        // Now you can use the `model` object to label sentences. 
        model.classify(['you suck']).then(predictions => {
          console.log(predictions)
        });
    });
  })

  return (
    <>
      <Head>
        <title>Smart-Forums</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />


      </Head>
      <main>
        hello 
      </main>
    </>
  )
}
