import { useState, useEffect} from 'react';
import * as toxicity from '@tensorflow-models/toxicity';

import Head from 'next/head'
import Image from "next/image";

// Styles
import styles from "@/styles/index.module.css"

// Assets
import sganyani from '../../public/sganyani.png'

// Icons
import { BiSearch, BiMessageSquareAdd } from 'react-icons/bi'
import { BsBookmark } from 'react-icons/bs'
// import { PiSubtitles } from 'react-icons/pi'

  // Components
import Thread from '@/components/thread/index'
import Backdrop from "@/hoc/backdrop/backdrop"

// Data
import { threads } from '@/data'

// Assets:Icons
// import { FaArrowLeftLong, FaTimeline } from 'react-icons/fa';
// import { BsVectorPen } from 'react-icons/bs';
// import { MdKeyboardArrowLeft, MdViewTimeline } from 'react-icons/md';

export default function Home() {
  const [reply, setReply] = useState(false)

  const FILTERS = [
    {
      name : "Description",
      icon: ""
    }, 
    { 
      name : "Topic",
      icon: ""
    }, 
    { 
      name : "Session | Year | Paper",
      icon: ""
    }
  ]

  const REGISTERED_COURSES = [
    {
      name : "Principles of Computer Science",
      code: "CSC201",
      image: "biology"
    },
    {
      name : "Introduction to Biology",
      code: "BIO101",
      image: "biology"
    }
]

  return (
    <>
      <Head>
        <title>Smart-Forums</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Backdrop reply={reply} setReply={setReply} />
      <main>
        <section className={styles.nav}>
            <div className={styles.title}>
                <p> Discussion Forums / Chemistry </p>
                <div className={styles.backArrow}>
                    {/* <MdKeyboardArrowLeft className={styles.icon} color="#0058FF" /> */}
                    <p>dashboard</p>
                </div>
            </div>

            <div className={styles.profile}>
                <Image className={styles.avatar} src={sganyani} alt="user-avatar" />
                {/* <BiDotsVerticalRounded className={styles.icon} /> */}
            </div>
        </section>
        {/* // Mid Section */}
        <section className={styles.midSection}>
          <section className={styles.sideBar}>
              <div className={styles.wrap}>
                  <div className={styles.head}>
                      <i className="fa-regular fa-bars"></i>
                      <p>Registered Courses</p>
                  </div>
                  <div className={styles.registeredCourses}>
                      {
                          REGISTERED_COURSES.map((course, index) => {
                              return (
                                  <div className={styles.course} key={index}>
                                      <Image className={styles.avatar} src={`/${course.image}.jpg`} width={50} height={50} alt="course cover photo" />
                                      <div className={styles.courseMeta}>
                                          <p className={styles.courseName}>
                                              { course.name }
                                          </p>
                                          <p className={styles.courseCode}>
                                              { course.code }
                                          </p>
                                      </div>
                                  </div>
                              )
                          })
                      }
                  </div>
              </div>
              {/* Filters */}
              <div className={styles.filters}>
                  <div className={styles.head}>
                      {/* <i className="fa-solid fa-magnifying-glass"></i> */}
                      <p>Filters</p>
                  </div>
                  <section className={styles.filtersList}>
                      {
                          FILTERS.map((filter, index)=> {
                              return (
                                  <div className={styles.radioContainer} key={index}>
                                    {/* {
                                        filter.name === "Description"?<BsVectorPen className={styles.icon} /> : filter.name === "Topic"?<BsVectorPen className={styles.icon}/>:<MdViewTimeline className={styles.icon} />
                                    } */}
                                    <p>{ filter.name }</p>
                                  </div>
                              )
                          })
                      }
                  </section>
              </div>
          </section>
          <section className={styles.content}>
              {/* Controls */}
              <div className={styles.controls}>
                  <p className={styles.placeholderDescription}></p> 
                  <div className={styles.frSearch}>
                      {/* Filter threads */}
                      <button type="submit" className={styles.searchIcon}>
                        <BiSearch color="#808080" />
                      </button>
                      <input className={styles.input} placeholder="Search..." />  
                  </div>
                  {/* Filter saved posts */}
                  <div className={styles.controlsBtn}>
                    <BsBookmark color='#808080' />
                  </div>
                  {/* Add new post */}
                  <div className={styles.controlsBtn} onClick={()=>setReply(true)}>
                    <BiMessageSquareAdd color='#808080' />
                  </div>

                  <div className={styles.filter}>
                    default
                  </div>
              </div>
              <div className={styles.threads}>
                {
                  threads.map((thread, index) => {
                      return <Thread key={index}  thread={thread}  setReply={setReply}/> })
                }
              </div>
          </section>
        </section>
      </main>
    </>
  )
}
